- name: Install sysstat
  ansible.builtin.apt:
    name: sysstat
    state: present

- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present

- name: Download install.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/snappyflow/apm-agent/master/install.sh
    dest: /tmp/install.sh
    validate_certs: yes

- name: change permissions
  become: yes
  vars:
    ansible_become_password: Maplelabs@123
  ansible.builtin.command:
    cmd: chmod +x /tmp/install.sh

- name: Install sfAgent
  become: yes
  vars:
    ansible_become_password: Maplelabs@123
  ansible.builtin.command:
    cmd: /bin/bash /tmp/install.sh
  register: install_output

- name: Print output of Install sfAgent
  ansible.builtin.debug:
    var: install_output

- name: Generate config
  become: yes
  vars:
    ansible_become_password: Maplelabs@123
  ansible.builtin.command:
    cmd: ./sfagent -generate-config
    chdir: /opt/sfagent
  register: sfAgent_config

  
- name: Print generated config output
  ansible.builtin.debug:
    var: sfAgent_config.stdout_lines
  when: sfAgent_config.changed

- name: Copy generated config
  become: yes
  vars:
    ansible_become_password: Maplelabs@123
  ansible.builtin.copy:
    src: /opt/sfagent/config-generated.yaml
    dest: /opt/sfagent/config.yaml
    remote_src: yes


