- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present

- name: Template Nginx configuration file
  become: yes
  vars:
    ansible_become_password: Maplelabs@123
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
      
- name: restart nginx
  become: yes
  vars:
    ansible_become_password: Maplelabs@123
  ansible.builtin.service:
    name: nginx
    state: restarted